### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by starseeker** [andreacasalino/Fast-Quick-hull#5]
Hi!  Can you tell us what the license is for this project?  Apologies if I missed it, but I wasn't seeing a license file or note in the header.

**Comment by andreacasalino** [comment]
Hi,

first of all thank you for the interest in this project. 
As you correctly pointed out, a LICENSE was missing. I have added a GNU one in [this PR](https://github.com/andreacasalino/Fast-Quick-hull/pull/7), which also contains some 
improvements to the code.

You are more than welcome to report any other issue.
Andrea

**Comment by andreacasalino** [comment]
I will re-open it if needed

**Comment by starseeker** [comment]
Hi - thanks for adding the LICENSE file.  For our proposed use case, GPL would be too restrictive - would Apache version 2 be an option?  Completely understand if GPL is preferred, just wanted to inquire if it was an option.

**Comment by andreacasalino** [comment]
Hey,

I guess you would prefer Apache v.2 cause you want to change/tailor the code a bit more for your needs.
That is perfectly fine, I can update the license file.

On this front, consider also that you are more than welcome to propose changes and open PRs to this repository or require features that I would be happy to develop for you.

Finally and just for my curiosity, I would be also interested in learning more about the project(s) you are working on that may require the usage of Fast Quick Hull. Could you please spend a bit words (you can also approach me on this email andrecasa91@gmail.com if you don't want to do it in this thread) on that?

**Comment by starseeker** [comment]
> Hey,
> 
> I guess you would prefer Apache v.2 cause you want to change/tailor the code a bit more for your needs.
> That is perfectly fine, I can update the license file.

Great, thank you!


> On this front, consider also that you are more than welcome to propose changes and open PRs to this repository or require features that I would be happy to develop for you.

Much appreciated!

> Finally and just for my curiosity, I would be also interested in learning more about the project(s) you are working on that may require the usage of Fast Quick Hull. Could you please spend a bit words (you can also approach me on this email andrecasa91@gmail.com if you don't want to do it in this thread) on that?

Sure. The Manifold mesh library https://github.com/elalish/manifold uses quickhull as part of its processing,  and one of the possible Google summer of code projects they have is to improve performance and robustness of their current quickhull implementation.  Your project came up as one of the possibilities to try, which was why I inquired about the license - doesn't matter how good the implementation is if we can't use it,  so license questions are always the first to sort out. 

Manifold has demonstrated some very impressive results when it comes to robust mesh boolean operations,  so anything to make it more solid and fast is of interest.   The current quickhull implementation is known to fail in at least a few extreme cases (if I recall correctly,  small super thin manifold meshes might be one of them.)

**Comment by andreacasalino** [comment]
Hi,

Cool! That is an interesting project.

I have changed the license to be apache v2 in [this PR](https://github.com/andreacasalino/Fast-Quick-hull/pull/8/files).

Don't hesitate to open new issue if you will spot any other problems,
Andrea

**Comment by starseeker** [comment]
Awesome - thank you!

**Comment by andreacasalino** [comment]
Pls remember to leave a star when you have time.

Thanks,
Andrea
